# Generated by Django 2.1.2 on 2018-11-09 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=30)),
                ('ride_date', models.DateTimeField()),
                ('distance', models.FloatField(null=True)),
                ('average_speed', models.FloatField(null=True)),
                ('average_watts', models.FloatField(null=True)),
                ('average_heartrate', models.FloatField(null=True)),
                ('max_heartrate', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStream',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Activity')),
                ('time', models.FileField(upload_to='activities')),
                ('latlng', models.FileField(upload_to='activities')),
                ('distance', models.FileField(upload_to='activities')),
                ('altitude', models.FileField(upload_to='activities')),
                ('celocity_smooth', models.FileField(upload_to='activities')),
                ('heartrate', models.FileField(upload_to='activities')),
                ('cadende', models.FileField(upload_to='activities')),
                ('watts', models.FileField(upload_to='activities')),
                ('temp', models.FileField(upload_to='activities')),
                ('moving', models.FileField(upload_to='activities')),
                ('grade_smooth', models.FileField(upload_to='activities')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
